# Generated by Django 5.2.3 on 2025-07-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyview',
            name='story',
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storyview',
            name='viewer',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='posts/images/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='StoryView',
        ),
    ]
